{% set name = "kernel_driver" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c3cd5649321fc1e9ffcc0e7811af93e8aefcccb0cc48cf3002f8302675358c04

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - pyzmq
    - python-dateutil
    - rich

test:
  imports:
    - kernel_driver

about:
  home: https://github.com/davidbrochart/kernel_driver
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A library for executing code in a Jupyter kernel
  dev_url: https://github.com/davidbrochart/kernel_driver

extra:
  recipe-maintainers:
    - davidbrochart
